sudo: false
language: node_js
node_js:
- '0.10'
deploy:
- provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: iv6gvsFY9H1OL2aHpnu2W9YpzD8OoiEfR/3PFwXWc7q4m0cstRxKmHgkhxVRSfYSe7YY4ySNrXTXZaKNG9PpDKBHNN6QnbhdYLeHPZW3y2hv6cMolPNqCqh8I4TfXNa0Xgg+POcNxGJyd28JlzNeb2RZVHceCq+El1W36hNz0DlC+POS3uVnD7omcaO+SCcK43VlGxrItJQbqzanr2sefI4Gf6OYYqbxNPrVxQipQzxgAf4T9MVSiHALp5AHWxH984+Xs3QfdENmwNwZ3RXYjbzG2Xiv7gFHnilWuQHubdXWOzjER2lvMRbuHjp6HTm5lrcx7J0G2hJ1vuRSbnhsPi2ruFTkRenwUMfKKVBq7pJY2DPrLySup2GgNKQxJhLIlkAaN456st0XxPvFQTSXVOJTRh/K6QoQgngfDInjbjLXGNBfyQghsFyaaujD0tRqvRSrIY6XqGH1gW6ams0vEGhBhoqj2V+Xdq8we88H/HZnt3iGVBDTVr8IISmwgf5FbMOx3PpQl5wLNMam4O5fCsCKUGkETMrENy19OxU4Ohz+qrkTu6cnCMXLuQKafWLAjqusoruMRqBRKnJ/eoWSD/X6huTSMspHfP7WTa36mq7XzIOlCeJnUqVUusAdJvMEn5ah7J8dQBaYIHX/DnxqTWJd0kPSLXEPCMSfoJOU88E=
  on:
    tags: true
    all_branches: true
